# Generated by Django 5.0.2 on 2024-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_model',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
